name: lint
on:
  push:
    branches:
      - main
      - dev
      - "KAFI-[0-9]*/KAFI-[0-9]*"
      - "*/KAFI-[0-9]*/KAFI-[0-9]*"
  pull_request:
    branches:
      - main
      - dev
      - "KAFI-[0-9]*/KAFI-[0-9]*"
      - "*/KAFI-[0-9]*/KAFI-[0-9]*"
    paths-ignore:
      - "README.md"
      - "LICENSE"
jobs:
  lint-prettier:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22"

      - name: Install dependencies
        run: pnpm install

      - name: Run ESLint
        run: pnpm lint
